### ISSUE TITLE
arbitrary-network is a strong depenency

### ISSUE THREAD

**Issue by samoht** [yomimono/ocaml-nat#5]
The project does not compile without `arbitrary-network`, we should either fix the opam or the _oasis file.

**Comment by yomimono** [comment]
What I'd like to do is break the strong dependency, since we only need 
it for tests (and only a small subset of those, for that matter), which 
most people don't care about.

**Comment by yomimono** [comment]
It's now possible to build the project without `arbitrary-network`.
